GET http://localhost:3000

###
GET http://localhost:3000/category
Authorization: Bearer 123456

###

POST http://localhost:3000/category
Authorization: Bearer 123456
content-type: application/json

{
    "alias": "bakery-1",
    "title": "Bakery 1"
}

###
POST http://localhost:3000/business
Authorization: Bearer 123456
content-type: application/json

{
    "name": "test kitchen",
    "alias": "test-4",
    "phone": "0987766",
    "categories": [1, 2, 3]
}

###
PUT http://localhost:3000/business/0758f772-c5cd-4c23-88d8-3499400aafa7
Authorization: Bearer 123456
content-type: application/json

{
    "name": "Katz's Delicatessen update",
    "alias": "katzs-delicatessen-new-york update",
    "phone": "09877667"
}

###
DELETE http://localhost:3000/business/236fe09f-4648-4f7c-8e4d-eb469c9cac3b
Authorization: Bearer 123456

###
GET http://localhost:3000/business/search?location='test'
Authorization: Bearer 123456